openapi: '3.1.0'
info:
  title: EmailKit
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Server for local development
paths:
  /api/v1/email/search:
    get:
      operationId: getSearch
      parameters:
        - $ref: '#/components/parameters/mailbox'
        - $ref: '#/components/parameters/criteria'
      responses:
        '200':
          description: A success response with a search query.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResults'
  /api/v1/email/health:
    get:
      operationId: getHealth
      responses:
        '200':
          description: A success response with a health status.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
components:
  parameters:
    mailbox:
      name: mailbox
      in: query
      required: true
      description: The name of the inbox you would like to search
      schema:
        type: string
    criteria:
      name: criteria
      in: query
      required: true
      description: A JSON object defining the search criteria.
      schema:
        type: string
      style: form
      explode: false
  schemas:
    SearchCriteriaQuery:
      description: The contents of a search query
      type: object
      content:
        application/json:
      properties:
        simple:
          type: array
          items:
            type: string
        singleValue:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/SingleValueSearch'
      required:
        - simple
        - singleValue
    SearchCriteriaType:
      description: The supported search criteria
      oneOf:
      - type: object
        properties:
          type:
            type: string
            enum:
              - dateBefore
              - dateOn
              - bodyContaining
              - from
              - keyword
              - sentOn
              - subject
              - since
              - text
              - uID
        required:
          - type
    SingleValueSearch:
      description: A search criteria supporting a single string value
      type: object
      properties:
        criteriaType:
          type: object
          description: the type of search criteria i.e text
          $ref: '#/components/schemas/SearchCriteriaType'
        value:
          type: string
          description: the value to search by
      required:
        - criteriaType
        - value
    SearchResults:
      description: An array of messages based on the provided search criteria
      type: array
      items:
        type: object
        $ref: '#/components/schemas/EmailMessage'
    EmailMessage:
      type: object
      description: A type meant to hold the email header & part structure information
      properties:
        sequenceNumber:
          type: integer
          description: SequenceNumber of the email message
        uID:
          description: UID of the email message
          type: integer
        subject:
          description: The subject of the message
          type: string
        from:
          description: The sender of the message
          type: string
        to:
          description: The recipients of the message
          type: string
        date:
          description: The date of the message
          type: string
          format: date
        parts:
          description: The recipients of the message
          type: array
          items:
            type: object
            $ref: '#/components/schemas/MessagePart'
      required:
        - sequenceNumber
        - parts
    MessagePart:
      type: object
      description: A part of an email message
      properties:
        section:
            type: string
            description: The section number (e.g., [1, 2, 3] represents "1.2.3")
        contentType:
          type: string
          description: The content type of the part (e.g., "text/html", "image/jpeg")
        disposition:
          type: string
          description: The content disposition (e.g., "inline", "attachment")
        encoding:
          type: string
          description: The content transfer encoding (e.g., "base64", "quoted-printable")
        filename:
          type: string
          description: The filename of the part (if any)
        contentId:
          type: string
          description: The content ID of the part (if any)
        data:
          type: string
          description: The raw content data (if any)
        decodedData:
          type: string
          description: The decoded data (if any)
      required:
        - section
        - contentType
    Health:
      type: object
      description: A value with the health contents.
      properties:
        status:
          type: string
          description: The string representation of the health status.
      required:
        - status

